name: Discord Welcome Message

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "🇹🇷 **YENİLMEZLER SCUM SUNUCUSUNA HOŞ GELDİN!**\n\n☠️ Hayatta kalmaya hazır ol!\n🔥 4X LOOT sistemi aktif\n🛒 Market / Shop sistemi aktif\n🚫 Mechler kapalı\n⚔️ PvP & PvE bölgeleri mevcut\n🎁 Aktif etkinlikler ve ödüller\n💬 Dost canlısı topluluk & aktif admin desteği\n\n📢 Sunucu ile ilgili bütün bilgileri 𝑺𝒆𝒓𝒗𝒆𝒓𝒃𝒊𝒍𝒈𝒊-𝑰𝒏𝒇𝒐 kanalından alabilirsiniz.\n\nKurallara uy, ekibinle güçlen ve adanın hakimi ol!\nİyi oyunlar survivor 👊\n\n━━━━━━━━━━━━━━\n\n🇬🇧 **WELCOME TO YENILMEZLER SCUM SERVER!**\n\n☠️ Get ready to survive!\n🔥 4X Loot enabled\n🛒 Market / Shop system active\n🚫 Mechs disabled\n⚔️ PvP & PvE zones available\n🎁 Active events & rewards\n💬 Friendly community & active admin support\n\n📢 You can find all server information in the 𝑺𝒆𝒓𝒗𝒆𝒓𝒃𝒊𝒍𝒈𝒊-𝑰𝒏𝒇𝒐 channel.\n\nFollow the rules, build your squad, and dominate the island!\nGood luck survivor 👊"
          }' \
          https://discord.com/api/webhooks/1502011442809929810/4Xz8__YT8Y35aH6E9DFURa7IZAN18tN3Y1s9M7iTvPzZ-FRd28COf2fitc9hJ0H7D5pd
